/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/challenges/{id}/start": {
    /** Start a new sandbox session */
    post: operations["startSession"];
  };
  "/validate/{sessionId}": {
    /** Validate a running sandbox solution */
    post: operations["validateSession"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SessionResponse: {
      sessionId: string;
      challengeId: string;
      challengeTitle: string;
      terminalUrl: string;
      validateUrl: string;
      ttlMins: number;
    };
    CheckResult: {
      check_id: string;
      passed: boolean;
      message: string;
    };
    ValidationResponse: {
      passed: boolean;
      feedback?: string;
      checkResults?: components["schemas"]["CheckResult"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Start a new sandbox session */
  startSession: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Sandbox session started */
      200: {
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
    };
  };
  /** Validate a running sandbox solution */
  validateSession: {
    parameters: {
      path: {
        sessionId: string;
      };
    };
    responses: {
      /** @description Solution passed */
      200: {
        content: {
          "application/json": components["schemas"]["ValidationResponse"];
        };
      };
      /** @description Solution failed */
      422: {
        content: {
          "application/json": components["schemas"]["ValidationResponse"];
        };
      };
    };
  };
}
