// Re-exports from the shared @devops/types package.
// All app code that needs shared API types should import from here (@/lib/api-types)
// rather than directly from @devops/types, so there is a single local alias to update
// if the package name ever changes.
export type {
  ApiResult,
  ApiSuccess,
  ApiFailure,
  Challenge,
  Session,
  UserSession,
  Roadmap,
  RoadmapNode,
  RoadmapProgress,
  QuizNode,
  QuizProgress,
  QuizQuestion,
  QuizMetadata,
  QuizAttempt,
  SubmitResponse,
  SubmissionHistory,
  ValidationResult,
  ValidationResponse,
  FlashcardDeck,
  Flashcard,
  HistoryItem,
  StandardResponse,
  DashboardData,
  SandboxHealth,
  CheckResult,
  AssistantMessage,
  OnboardingStatus,
  SecurityLogEntry,
  SecurityLogResponse,
  ActiveSession,
  UserProfile,
  MfaSetupResponse,
} from "@devops/types";
