export const API_ROUTES = {
  auth: {
    publicKey: "/api/auth/public-key",
    guestToken: "/api/auth/guest-token",
    login: "/api/auth/login",
    loginSso: "/api/auth/login/sso",
    loginMfa: "/api/auth/login/mfa",
    register: "/api/auth/register",
    verifyEmail: "/api/auth/verify-email",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    refresh: "/api/auth/refresh",
    exchange: "/api/auth/exchange",
    me: "/api/auth/me",
    changePassword: "/api/auth/change-password",
    logout: "/api/auth/logout",
    logoutAll: "/api/auth/logout-all",
    securityLog: "/api/auth/security-log",
    sessions: "/api/auth/sessions",
    revokeSession: (sessionId: string) => `/api/auth/sessions/${sessionId}/revoke`,
    mfaSetup: "/api/auth/mfa/setup",
    mfaVerify: "/api/auth/mfa/verify",
    oauthGithubCallback: "/api/auth/login/github/callback",
    oauthGoogleCallback: "/api/auth/login/google/callback",
    history: "/api/me/history",
    dashboard: "/api/me/dashboard",
  },
  challenges: {
    base: "/api/challenges",
    byId: (id: string) => `/api/challenges/${id}`,
    editorial: (id: string) => `/api/challenges/${id}/editorial`,
    start: (id: string) => `/api/challenges/${id}/start`,
    trial: (id: string) => `/api/challenges/${id}/trial`,
    trialStatus: (id: string) => `/api/challenges/${id}/trial/status`,
    history: (id: string) => `/api/me/challenges/${id}/history`,
    like: (id: string) => `/api/challenges/${id}/like`,
    bookmark: (id: string) => `/api/challenges/${id}/bookmark`,
    interactions: (id: string) => `/api/challenges/${id}/interactions`,
  },
  sessions: {
    byId: (id: string) => `/api/session/${id}`,
    health: (sessionId: string) => `/api/session/${sessionId}/health`,
    checkResults: (sessionId: string) => `/api/session/${sessionId}/check-results`,
    terminateActive: "/api/session/active",
  },
  onboarding: {
    status: "/api/challenges/onboarding-status",
    complete: "/api/challenges/onboarding-status/complete",
  },
  roadmaps: {
    base: "/api/content/roadmaps",
    bySlug: (slug: string) => `/api/content/roadmaps/${slug}`,
    progress: (slug: string) => `/api/me/roadmaps/${slug}/progress`,
  },
  quizzes: {
    base: "/api/content/quizzes",
    allHistory: "/api/content/quizzes/history",
    byId: (id: string) => `/api/content/quizzes/${id}`,
    bySlug: (slug: string) => `/api/content/quizzes/${slug}`,
    submit: (slug: string) => `/api/content/quizzes/${slug}/submit`,
    progress: (slug: string) => `/api/me/quizzes/${slug}/progress`,
    history: (slug: string) => `/api/content/quizzes/${slug}/history`,
    editorial: (slug: string) => `/api/content/quizzes/${slug}/editorial`,
  },
  flashcards: {
    base: "/api/content/flashcards",
  },
  nodes: {
    byId: (id: string) => `/api/content/nodes/${id}`,
    parents: (id: string) => `/api/content/nodes/${id}/parents`,
    children: (id: string) => `/api/content/nodes/${id}/children`,
    ancestors: (id: string) => `/api/content/nodes/${id}/ancestors`,
    userFrontier: (userId: string) => `/api/content/users/${userId}/frontier`,
  },
  articles: {
    base: "/api/articles",
    bySlug: (slug: string) => `/api/articles/${slug}`,
    create: "/api/articles",
    like: (id: string) => `/api/articles/${id}/like`,
    bookmark: (id: string) => `/api/articles/${id}/bookmark`,
    report: (id: string) => `/api/articles/${id}/report`,
  },
  assistant: {
    chat: "/api/assistant/chat",
  },
  leaderboard: {
    base: "/api/leaderboard",
    byOrg: (orgId: string) => `/api/orgs/${orgId}/leaderboard`,
  },
  orgs: {
    base: "/api/orgs",
    me: "/api/orgs/me",
    members: (orgId: string = "me") => `/api/orgs/${orgId}/members`,
    invites: (orgId: string = "me") => `/api/orgs/${orgId}/invites`,
    analytics: (orgId: string = "me") => `/api/orgs/${orgId}/analytics`,
    scenarios: (orgId: string = "me") => `/api/orgs/${orgId}/scenarios`,
    assignments: (orgId: string = "me") => `/api/orgs/${orgId}/assignments`,
    matrix: (orgId: string = "me") => `/api/orgs/${orgId}/assignments/matrix`,
    complianceExport: (orgId: string = "me") => `/api/orgs/${orgId}/compliance-export`,
    join: (token: string) => `/api/orgs/join/${token}`,
  },
  users: {
    profile: (username: string) => `/api/users/${username}/profile`,
    follow: (userId: string) => `/api/users/${userId}/follow`,
    feed: "/api/users/me/feed",
    bookmarks: "/api/users/me/bookmarks",
    following: "/api/users/me/following",
    discover: "/api/users/discover",
  },
  shares: {
    base: "/api/shares",
    byToken: (token: string) => `/api/shares/${token}`,
  },
  comments: {
    byChallenge: (challengeId: string) => `/api/challenges/${challengeId}/comments`,
    vote: (commentId: string) => `/api/comments/${commentId}/vote`,
    delete: (commentId: string) => `/api/comments/${commentId}`,
  },
  lists: {
    base: "/api/lists",
    byId: (id: string) => `/api/lists/${id}`,
    addItem: (id: string) => `/api/lists/${id}/items`,
    removeItem: (id: string, challengeId: string) => `/api/lists/${id}/items/${challengeId}`,
  },
  sandbox: {
    terminal: (sessionId: string) => `/sessions/${sessionId}/terminal`,
    validate: (sessionId: string) => `/validate/${sessionId}`,
    workerHealth: (terminalUrl: string) =>
      terminalUrl.replace("ws://", "http://").replace("wss://", "https://").replace("/terminal", "/health"),
  },
  notification: {
    health: "/health",
  },
};
